language: "es"

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
    epochs: 100
  - name: EntitySynonymMapper
  - name: SklearnIntentClassifier
policies:
  - name: KerasPolicy
    max_history: 5
    epochs: 100
    batch_size: 50
    max_training_samples: 300
  - name: FallbackPolicy
    nlu_threshold: 0.15
    core_threshold: 0.1
    fallback_action_name: 'utter_no_te_entiendo'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
